name: trainings_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  go_router_builder: ^2.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  very_good_analysis: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true